export const branchesMenuRaw = [
  //mainCourse
  {
    id: 1,
    title: "Whole Wheat Pizza Crust",
    rate: 4,
    price: 23,
    image: "/mainCourse/Amazing Whole Wheat Pizza Crust.webp",
    discount: 20,
    category: "mainCourse",
  },
  {
    id: 2,
    title: "American Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/American Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 3,
    title: "Balsamic Chicken and Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Balsamic Chicken and Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 4,
    title: "BBQ Chicken Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/BBQ Chicken Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 5,
    title: "Black Bean Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Black Bean Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 6,
    title: "Broccoli Garlic Angel Hair Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Broccoli Garlic Angel Hair Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 7,
    title: "Cajun Seafood Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Cajun Seafood Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 8,
    title: "Champagne Shrimp and Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Champagne Shrimp and Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 9,
    title: "Cheese Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Cheese Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 10,
    title: "Chicken Alfredo Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Chicken Alfredo Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 11,
    title: "Chicken Avocado Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Chicken Avocado Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 12,
    title: "Classic Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Classic Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 13,
    title: "Creamy Pasta Bake with Cherry Tomatoes and Basil",
    rate: 3,
    price: 19,
    image: "/mainCourse/Creamy Pasta Bake with Cherry Tomatoes and Basil.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 14,
    title: "Creamy Sun-Dried Tomato Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Creamy Sun-Dried Tomato Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 15,
    title: "Crescent Pizza Pockets",
    rate: 3,
    price: 19,
    image: "/mainCourse/Crescent Pizza Pockets.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 16,
    title: "Deep-Dish Cast Iron Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Deep-Dish Cast Iron Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 17,
    title: "Easy Vegetarian Spinach Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Easy Vegetarian Spinach Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 18,
    title: "Eggplant Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Eggplant Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 19,
    title: "Eggs Benedict Breakfast Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Eggs Benedict Breakfast Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 20,
    title: "Flourless Eggplant Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Flourless Eggplant Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 21,
    title: "Greek Pizza with Spinach, Feta and Olives",
    rate: 3,
    price: 19,
    image: "/mainCourse/Greek Pizza with Spinach, Feta and Olives.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 22,
    title: "Hearty Vegetable Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Hearty Vegetable Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 23,
    title: "Hummus Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Hummus Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 24,
    title: "Lasagna Alfredo Roll Ups",
    rate: 3,
    price: 19,
    image: "/mainCourse/Lasagna Alfredo Roll Ups.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 25,
    title: "Pan-Seared Lemon Tilapia with Parmesan Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pan-Seared Lemon Tilapia with Parmesan Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 26,
    title: "Pasta alla Vodka",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pasta alla Vodka.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 27,
    title: "Pasta Fazool (Pasta e Fagioli)",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pasta Fazool (Pasta e Fagioli).webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 28,
    title: "pasta-con-sarde-pasta-with-sardines",
    rate: 3,
    price: 19,
    image: "/mainCourse/pasta-con-sarde-pasta-with-sardines.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 29,
    title: "Pesto Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pesto Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 30,
    title: "Penne Pasta with Spinach and Bacon",
    rate: 3,
    price: 19,
    image: "/mainCourse/Penne Pasta with Spinach and Bacon.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 31,
    title: "Pesto Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pesto Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 32,
    title: "Pesto Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Pesto Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 33,
    title: "shrimp-scampi-with-pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/shrimp-scampi-with-pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 34,
    title: "Savory Sea Scallops and Angel Hair Pasta",
    rate: 3,
    price: 19,
    image: "/mainCourse/Savory Sea Scallops and Angel Hair Pasta.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 35,
    title: "Spinach and Turkey Lasagna",
    rate: 3,
    price: 19,
    image: "/mainCourse/Spinach and Turkey Lasagna.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 36,
    title: "Spinach Lasagna Roll Ups",
    rate: 3,
    price: 19,
    image: "/mainCourse/Spinach Lasagna Roll Ups.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 37,
    title: "Taco Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Taco Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 38,
    title: "Veggie Pizza",
    rate: 3,
    price: 19,
    image: "/mainCourse/Veggie Pizza.webp",
    discount: 10,
    category: "mainCourse",
  },
  {
    id: 39,
    title: "Zucchini Pizza Bake",
    rate: 3,
    price: 19,
    image: "/mainCourse/Zucchini Pizza Bake.webp",
    discount: 10,
    category: "mainCourse",
  },
  //drinks
  {
    id: 40,
    title: "Cranberry Wassail",
    rate: 5,
    price: 4,
    image: "/drinks/Cranberry Wassail.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 41,
    title: "Eggnog Latte",
    rate: 5,
    price: 4,
    image: "/drinks/Eggnog Latte.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 42,
    title: "Gingerade",
    rate: 5,
    price: 4,
    image: "/drinks/Gingerade.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 43,
    title: "Green Punch",
    rate: 5,
    price: 4,
    image: "/drinks/Green Punch.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 44,
    title: "Hot Buttered Rum",
    rate: 5,
    price: 4,
    image: "/drinks/Hot Buttered Rum.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 45,
    title: "Mexican Strawberry Water (Agua de Fresa)",
    rate: 5,
    price: 4,
    image: "/drinks/Mexican Strawberry Water (Agua de Fresa).webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 46,
    title: "Mocha Coffee Mix",
    rate: 5,
    price: 4,
    image: "/drinks/Mocha Coffee Mix.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 47,
    title: "Pumpkin Spice Coffee",
    rate: 5,
    price: 4,
    image: "/drinks/Pumpkin Spice Coffee.webp",
    discount: 12,
    category: "drinks",
  },
  {
    id: 48,
    title: "Vintage Lemonade",
    rate: 5,
    price: 4,
    image: "/drinks/Vintage Lemonade.webp",
    discount: 12,
    category: "drinks",
  },
  //desserts
  {
    id: 49,
    title: "Apple Crisp",
    rate: 4,
    price: 8,
    image: "/desserts/Apple Crisp.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 50,
    title: "Cinnamon Nutmeg Coffee Cake",
    rate: 4,
    price: 8,
    image: "/desserts/Cinnamon Nutmeg Coffee Cake.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 51,
    title: "Coconut Milk Ice Cream",
    rate: 4,
    price: 8,
    image: "/desserts/Coconut Milk Ice Cream.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 52,
    title: "Cottage Cheese Blueberry Breakfast Cake",
    rate: 4,
    price: 8,
    image: "/desserts/Cottage Cheese Blueberry Breakfast Cake.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 53,
    title: "No-Bake Millionaire’s Shortbread",
    rate: 4,
    price: 8,
    image: "/desserts/No-Bake Millionaire’s Shortbread.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 54,
    title: "Pavlova Christmas Trees",
    rate: 4,
    price: 8,
    image: "/desserts/Pavlova Christmas Trees.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 55,
    title: "Strawberry Brownies",
    rate: 4,
    price: 8,
    image: "/desserts/Strawberry Brownies.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 56,
    title: "Tahini Butter Cookies",
    rate: 4,
    price: 8,
    image: "/desserts/Tahini Butter Cookies.webp",
    discount: 14,
    category: "desserts",
  },
  {
    id: 57,
    title: "Tiramisu Blondies",
    rate: 4,
    price: 8,
    image: "/desserts/Tiramisu Blondies.webp",
    discount: 14,
    category: "desserts",
  },
  //appetizers
  {
    id: 58,
    title: "Apple Spinach Salad",
    rate: 5,
    price: 12,
    image: "/appetizers/Apple Spinach Salad.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 59,
    title: "Artichoke Parmesan Soup",
    rate: 5,
    price: 12,
    image: "/appetizers/Artichoke Parmesan Soup.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 60,
    title: "Carrot Raisin Salad",
    rate: 5,
    price: 12,
    image: "/appetizers/Carrot Raisin Salad.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 61,
    title: "Cheesy Taco Soup",
    rate: 5,
    price: 12,
    image: "/appetizers/Cheesy Taco Soup.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 62,
    title: "Creamy Tomato Bean Soup",
    rate: 5,
    price: 12,
    image: "/appetizers/Creamy Tomato Bean Soup.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 63,
    title: "Crispy Buffalo Potato Salad",
    rate: 5,
    price: 12,
    image: "/appetizers/Crispy Buffalo Potato Salad.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 64,
    title: "Green Goddess Salad",
    rate: 5,
    price: 12,
    image: "/appetizers/Green Goddess Salad.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 65,
    title: "Hearts of Palm and Avocado Salad",
    rate: 5,
    price: 12,
    image: "/appetizers/Hearts of Palm and Avocado Salad.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 66,
    title: "High Protein Broccoli Cheddar Soup",
    rate: 5,
    price: 12,
    image: "/appetizers/High Protein Broccoli Cheddar Soup.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 67,
    title: "Lobster-Vanilla Bean Bisque",
    rate: 5,
    price: 12,
    image: "/appetizers/Lobster-Vanilla Bean Bisque.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 68,
    title: "Roasted-Cherry-Tomato-Soup",
    rate: 5,
    price: 12,
    image: "/appetizers/Roasted-Cherry-Tomato-Soup.webp",
    discount: 10,
    category: "appetizers",
  },
  {
    id: 69,
    title: "Watermelon Salad with Feta",
    rate: 5,
    price: 12,
    image: "/appetizers/Watermelon Salad with Feta.webp",
    discount: 10,
    category: "appetizers",
  },
];

export const branchesMenu = branchesMenuRaw.map((item) => ({
  ...item,
  priceAfterDiscount: item.price - (item.price * item.discount) / 100,
}));
