import TanstackQueryProvider from "@/components/partials/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";

import Layout from "@/components/layout/Layout";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
			<TanstackQueryProvider>
			<Layout>
				{children}
				</Layout>
			</TanstackQueryProvider>
			<Toaster/>
				
				
				</body>
		</html>
	);
}
