import TanstackQueryProvider from "@/components/provider/TanstackQueryProvider";
import { Toaster } from "react-hot-toast";


import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata = {
	title: "Mehmoni | Food Shop",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<TanstackQueryProvider>
					<Header/>
					{children}
					<Footer/>
				</TanstackQueryProvider>
				<Toaster />
			</body>
		</html>
	);
}
